---
- name: install packages
  with_items: "{{ znc_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart znc

- name: enable znc service
  template:
    src: znc.j2
    dest: /etc/rc.conf.d/znc
